export default {
  normal: { name: "Normal", color: '#A8A878' },
  fighting: { name: "Fighting", color: '#C03028' },
  flying: { name: "Flying", color: '#A890F0' },
  poison: { name: "Poison", color: '#A040A0' },
  ground: { name: "Ground", color: '#E0C068' },
  rock: { name: "Rock", color: '#B8A038' },
  bug: { name: "Bug", color: '#A8B81F' },
  ghost: { name: "Ghost", color: '#705898' },
  steel: { name: "Steel", color: '#B8B8D0' },
  fire: { name: "Fire", color: '#F08030' },
  water: { name: "Water", color: '#6890F0' },
  grass: { name: "Grass", color: '#78C850' },
  electric: { name: "Electric", color: '#F8D030' },
  psychic: { name: "Psychic", color: '#F85888' },
  ice: { name: "Ice", color: '#98D8D8' },
  dragon: { name: "Dragon", color: '#7038F8' },
  dark: { name: "Dark", color: '#705848' },
  fairy: { name: "Fairy", color: '#EE99AC' },
  unknown: { name: "Unknown", color: '#68A090' },
  shadow: { name: "Shadow", color: '#592359' },
}
