export default {
  'red-blue': 'Red and Blue',
  yellow: 'Yellow',
  'gold-silver': 'Gold and Silver',
  crystal: 'Crystal',
  'ruby-sapphire': 'Ruby and Sapphire',
  emerald: 'Emerald',
  'firered-leafgreen': 'FireRed and LeafGreen ',
  'diamond-pearl': 'Diamond and Pearl',
  platinum: 'Platinum',
  'heartgold-soulsilver': 'HeartGold and Soulsiver',
  'black-white': 'Black and White',
  colosseum: 'Colosseum',
  xd: 'XD',
  'black-2-white-2': 'Black 2 and White 2',
  'x-y': 'X and Y',
  'omega-ruby-alpha-sapphire': 'Omega Ruby and Alpha Sapphire',
  'sun-moon': 'Sun and Moon',
  'ultra-sun-ultra-moon': 'Ultra Sun and Ultra Moon',
  'lets-go': 'Lets Go',
  'sword-shield': 'Sword and Shield',
}
